#!/usr/bin/env python3
"""P2 write-path harness (Python-in-the-loop): pulse -> driver -> SOT write branch.

For each DAC amplitude it runs an ngspice TRANSIENT of {ideal pulse -> driver output
resistance Rdrv -> smtj_sot write branch}, then from the waveforms:
  * integrates SOT-channel energy and driver(Rdrv) energy,
  * extracts the delivered flat-top write voltage -> P_sw,
  * does a seeded Bernoulli write (harness-owned RNG) for the stochastic-write demo.

Quantifies (P2): driver overhead on the 0.78 pJ Ohmic write energy (errata R4),
0.75 ns pulse deliverability across 776 ohm (driver output-impedance constraint),
and P_sw reproduction. Real sky130 CMOS driver replaces Vpulse+Rdrv later.

Run:  python eda/testbenches/write_mc_harness.py
Tools via env OPENVAF/NGSPICE or eda/tools.local.json (see SETUP_opensource.md).
"""
from __future__ import annotations
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

trapz = getattr(np, "trapezoid", np.trapz)   # numpy>=2 renamed trapz -> trapezoid

HERE = Path(__file__).resolve().parent
MODEL = HERE.parent / "models" / "smtj_sot.va"
CONFIG = HERE.parent / "tools.local.json"
OSDI = HERE / "smtj_sot.osdi"
RUN = HERE / "_write_run.spice"
TRAN = HERE / "write_tran.csv"

VTH, VT, RSOT = 0.895783, 0.023414, 776.0

NETLIST = """* P2 write-path auto-run (generated by write_mc_harness.py)
.model smtj_sot smtj_sot
Vpulse drvin 0 PULSE(0 {vamp} 0.2n {tr} {tr} {tw} 10n)
Rdrv drvin wr {rdrv}
Cwr  wr 0 {cwr}
Vcom com 0 dc 0
Vrd  rd  0 dc 0
Vst  st  0 dc 0
N1 wr rd com st psw tau sinf smtj_sot
Rpsw  psw  0 1e12
Rtau  tau  0 1e12
Rsinf sinf 0 1e12
.control
  tran 0.5p 4n
  wrdata write_tran.csv v(wr) v(drvin)
  quit
.endc
.end
"""


def _cfg():
    try:
        return json.loads(CONFIG.read_text()) if CONFIG.exists() else {}
    except Exception:
        return {}


def find_tool(env, key, names):
    v = os.environ.get(env)
    if v and Path(v).exists():
        return v
    c = _cfg().get(key)
    if c and Path(c).exists():
        return c
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    return None


def load_tran():
    rows = []
    for line in TRAN.read_text().splitlines():
        line = line.strip()
        if not line or line[0] in "*#":
            continue
        p = [x for x in line.replace(",", " ").split() if x]
        try:
            rows.append([float(x) for x in p])
        except ValueError:
            continue
    a = np.array(rows)
    return a[:, 0], a[:, 1], a[:, 3]      # t, v_wr, v_drvin (wrdata pairs x with each var)


def rise_time(t, v):
    vmax = v.max()
    if vmax <= 0:
        return float("nan")
    lo, hi = 0.1 * vmax, 0.9 * vmax
    t10 = t[np.argmax(v >= lo)]
    t90 = t[np.argmax(v >= hi)]
    return max(float(t90 - t10), 0.0)


def main():
    ng = find_tool("NGSPICE", "ngspice", ["ngspice_con", "ngspice"])
    ov = find_tool("OPENVAF", "openvaf", ["openvaf", "openvaf-r"])
    if not ng or not ov:
        print("ngspice/openvaf not found (env OPENVAF/NGSPICE or eda/tools.local.json). "
              "See eda/SETUP_opensource.md.")
        return 0
    subprocess.run([ov, str(MODEL), "-o", str(OSDI)], check=True, cwd=HERE)
    (HERE / ".spiceinit").write_text("osdi smtj_sot.osdi\n")

    rng = np.random.default_rng(20260626)
    N = 2000
    rdrv, cwr, tr, tw = 10.0, 5e-15, 0.05e-9, 0.75e-9
    print(f"driver: Rdrv={rdrv:.0f}ohm Cwr={cwr*1e15:.0f}fF  pulse tw={tw*1e9:.2f}ns tr={tr*1e9:.2f}ns")
    print("Vamp   v_flat  rise(ps)  E_sot(pJ) E_drv(pJ) ovhd%  P_sw   P_sw_mc")
    rowsout = []
    for vamp in np.round(np.arange(0.84, 0.951, 0.01), 3):
        RUN.write_text(NETLIST.format(vamp=vamp, tr=tr, tw=tw, rdrv=rdrv, cwr=cwr))
        subprocess.run([ng, "-b", RUN.name], check=True, cwd=HERE,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        t, vwr, vdrv = load_tran()
        esot = float(trapz(vwr ** 2 / RSOT, t))
        edrv = float(trapz((vdrv - vwr) ** 2 / rdrv, t))
        vflat = float(vwr.max())
        rt = rise_time(t, vwr)
        psw = 1.0 / (1.0 + np.exp(-(vflat - VTH) / VT))
        pmc = int(np.sum(rng.random(N) < psw)) / N
        ovhd = 100 * edrv / (esot + edrv) if (esot + edrv) > 0 else 0.0
        print(f"{vamp:.3f}  {vflat:.4f}  {rt*1e12:7.1f}  {esot*1e12:7.4f}  "
              f"{edrv*1e12:7.4f}  {ovhd:5.1f}  {psw:.3f}  {pmc:.3f}")
        rowsout.append(dict(vamp=float(vamp), v_flat=vflat, rise_ps=rt * 1e12,
                            esot_pJ=esot * 1e12, edrv_pJ=edrv * 1e12,
                            ovhd_pct=ovhd, psw=psw, psw_mc=pmc))

    summ = dict(driver=dict(Rdrv_ohm=rdrv, Cwr_fF=cwr * 1e15, tw_ns=tw * 1e9, tr_ns=tr * 1e9),
                seed=20260626, n_trials=N,
                note="first-cut: ideal pulse + series-R driver; sky130 CMOS driver later (P2)",
                rows=rowsout)
    (HERE / "write_summary.json").write_text(json.dumps(summ, indent=2))

    nom = [r for r in rowsout if abs(r["vamp"] - 0.90) < 1e-6]
    if nom:
        r = nom[0]
        print(f"\n@Vamp=0.90: delivered v_flat={r['v_flat']:.3f}V (divider across Rdrv+Rsot), "
              f"E_sot={r['esot_pJ']:.3f}pJ, E_drv={r['edrv_pJ']:.3f}pJ, overhead={r['ovhd_pct']:.1f}%, "
              f"rise={r['rise_ps']:.0f}ps << {tw*1e9:.2f}ns -> pulse feasible")


if __name__ == "__main__":
    main()
